### ISSUE TITLE
nvme_metrics.sh does not work at crontab

### ISSUE THREAD

**Issue by g00g1** [prometheus-community/node-exporter-textfile-collector-scripts#138]
When launch nvme_metrics.sh manually from shell, the script successfully returns metrics. But when I launch it from crontab using bash script, the execution fails with the error `nvme_metrics.sh: nvme is not installed. Aborting.` which is not true at all - I have nvme-cli installed and working, as well as jq.

As a temporary fix I have commented this if block, but this should be properly fixed at upstream, however I cannot figure out why this is happening.

**Comment by Impact123** [comment]
It's probably because it's not in the `PATH` of your cron job. One fix is using a full path, the other is to set `PATH` in your cron job.

**Comment by g00g1** [comment]
My bad, haven't seen that issue.

Yes, the issue was with PATH environment variable. Thank you for so quick reply!
