### ISSUE TITLE
smartmon collector missing node info

### ISSUE THREAD

**Issue by deajan** [prometheus-community/node-exporter-textfile-collector-scripts#156]
Hello,

Using the smartmon collector (bash version), I noticed that a quite important info is missing for me: the node name.

Indeed, I have about 30 disks in like 10 nodes, a couple of them being identical, and all called of course "/dev/sda" etc.
How can I know which node contains specific disk "/dev/sda" when there are multiple ones ?

Wouldn't adding hostname / nodename to all smart metrics be good ?

Best regards.

**Comment by dswarbrick** [comment]
Textfile collectors usually don't include a hostname label, since the metrics will automatically be stored with an `instance` label when the node_exporter is scraped by Prometheus.

**Comment by deajan** [comment]
Lol, I should have explored my data instead of relying on the dashboard. Indeed, I got the instance, I just had to fix my dashboard.
Shouldn't have posted an issue at 1pm... ;)
Sorry for the noise.
