### ISSUE TITLE
freeipmi collector?

### ISSUE THREAD

**Issue by filippog** [prometheus-community/node-exporter-textfile-collector-scripts#176]
Hi,
I've been using `ipmitool` collector and I've found an issue where `ipmitool sensor` is slow to run locally (long timeouts for sensors not found) while `ipmi-sensors` (from [freeipmi](http://savannah.gnu.org/projects/freeipmi/)) works well. A new collector adapted from the existing ipmitool one is easy enough to do, would you be interested in such a collector? I'm happy to send a PR if that's the case

**Comment by dswarbrick** [comment]
Given that there is already https://github.com/prometheus-community/ipmi_exporter, which uses freeipmi, and can probe both local and remote hosts, I think that yet another subtle variant would be redundant.

**Comment by filippog** [comment]
I see where you are coming from re: subtle variant. As a user, `ipmi_exporter` is certainly more powerful/capable and a whole lot more work to deploy too, especially when compared to the simplicity of `ipmitool` collector. At any rate, since there doesn't seem to be interest please feel free to close the issue.

I've included the code I'm using here: https://gist.github.com/filippog/b38efdf5db3be2c7ebb05f9398d3f7ea for folks that might come here in search of a similar solution

thank you !
