### ISSUE TITLE
nvme_metrics breaks on systems with more than 10 NVME drives

### ISSUE THREAD

**Issue by sknigh** [prometheus-community/node-exporter-textfile-collector-scripts#18]
https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/0be35b81fccdf74c731d9caacf3ec482af9e972e/nvme_metrics.sh#L53

The line that parses disk name will truncate when it reaches 10 (e.g. /dev/nvme10). This will cause the output to contain duplicate entries with different values.

In my use case, node_exporter will fill my logs with `error gathering metrics... was collected before with the same name and label values` and degrade the scrapes as a result.

**Comment by herver** [comment]
Mentioning explicitly PR #45 which addresses this issue
