### ISSUE TITLE
Issues with smartmon.py

### ISSUE THREAD

**Issue by candlerb** [prometheus-community/node-exporter-textfile-collector-scripts#23]
1. smartmon.py does not return the "raw" values of metrics (only cooked value/threshold/worst): but almost always the raw values are the meaningful ones.  e.g.

```
# HELP smartmon_attr_value SMART metric attr_value
# TYPE smartmon_attr_value gauge
smartmon_attr_value{name="reallocated_sector_ct",disk="/dev/sda"} 100
smartmon_attr_value{name="power_on_hours",disk="/dev/sda"} 97
smartmon_attr_value{name="power_cycle_count",disk="/dev/sda"} 99
smartmon_attr_value{name="wear_leveling_count",disk="/dev/sda"} 87
smartmon_attr_value{name="erase_fail_count_total",disk="/dev/sda"} 100
smartmon_attr_value{name="airflow_temperature_cel",disk="/dev/sda"} 70
smartmon_attr_value{name="total_lbas_written",disk="/dev/sda"} 99
```

None of those are meaningful.  For example, the power-on time is not 97 hours, and the temperature is not 70 degrees.  You have to trust that the nearer to zero it is, the worse it is.

Compare smartmon.sh:

```
smartmon_airflow_temperature_cel_raw_value{disk="/dev/sda",type="sat",smart_id="190"} 3.000000e+01
smartmon_airflow_temperature_cel_value{disk="/dev/sda",type="sat",smart_id="190"} 70
smartmon_erase_fail_count_total_raw_value{disk="/dev/sda",type="sat",smart_id="182"} 0.000000e+00
smartmon_erase_fail_count_total_value{disk="/dev/sda",type="sat",smart_id="182"} 100
smartmon_power_cycle_count_raw_value{disk="/dev/sda",type="sat",smart_id="12"} 6.000000e+00
smartmon_power_cycle_count_value{disk="/dev/sda",type="sat",smart_id="12"} 99
smartmon_power_on_hours_raw_value{disk="/dev/sda",type="sat",smart_id="9"} 1.094000e+04
smartmon_power_on_hours_value{disk="/dev/sda",type="sat",smart_id="9"} 97
smartmon_reallocated_sector_ct_raw_value{disk="/dev/sda",type="sat",smart_id="5"} 0.000000e+00
smartmon_reallocated_sector_ct_value{disk="/dev/sda",type="sat",smart_id="5"} 100
smartmon_total_lbas_written_raw_value{disk="/dev/sda",type="sat",smart_id="241"} 4.342395e+11
smartmon_total_lbas_written_value{disk="/dev/sda",type="sat",smart_id="241"} 99
smartmon_wear_leveling_count_raw_value{disk="/dev/sda",type="sat",smart_id="177"} 2.670000e+02
smartmon_wear_leveling_count_value{disk="/dev/sda",type="sat",smart_id="177"} 87
```

The cooked values are there too, but the raw ones are the useful ones (e.g. airflow temperature 30 degrees, power on hours 10940)

Aside: using named metrics like this is I think also better practice than having a shared metric "smartmon_attr_value" containing unrelated metrics (although since they are all cooked it's arguably OK)

2. With drives downstream of a megaraid card, smartmon.py doesn't give unique labels to each metric:

```
# HELP smartmon_device_active SMART metric device_active
# TYPE smartmon_device_active gauge
smartmon_device_active{disk="/dev/bus/0"} 1
smartmon_device_active{disk="/dev/bus/0"} 1
smartmon_device_active{disk="/dev/bus/0"} 1
smartmon_device_active{disk="/dev/bus/0"} 1
smartmon_device_active{disk="/dev/bus/0"} 1
...
```

Compare with smartmon.sh:

```
# HELP smartmon_device_active SMART metric device_active
# TYPE smartmon_device_active gauge
smartmon_device_active{disk="/dev/bus/0",type="sat+megaraid,10"} 1
smartmon_device_active{disk="/dev/bus/0",type="sat+megaraid,11"} 1
smartmon_device_active{disk="/dev/bus/0",type="sat+megaraid,12"} 1
smartmon_device_active{disk="/dev/bus/0",type="sat+megaraid,13"} 1
smartmon_device_active{disk="/dev/bus/0",type="sat+megaraid,14"} 1
...
```

-----

WORKAROUND:  use smartmon.sh instead.  (Bonus: it also works on older systems that don't have python3)

**Comment by paol** [comment]
It does publish raw values, here's a sample I just ran on my system:

```
smartmon_attr_raw_value{name="raw_read_error_rate",disk="/dev/sda"} 0
smartmon_attr_raw_value{name="reallocated_sector_ct",disk="/dev/sda"} 0
smartmon_attr_raw_value{name="power_on_hours",disk="/dev/sda"} 3453
smartmon_attr_raw_value{name="power_cycle_count",disk="/dev/sda"} 1409
smartmon_attr_raw_value{name="reported_uncorrect",disk="/dev/sda"} 0
...
```

**Comment by candlerb** [comment]
OK thanks, that's one issue out of the way.  That leaves duplicate timeseries for megaraid adapter.

Also: I still think smartmon.sh using named metrics is better than smartmon.py's generic metric `smartmon_attr_raw_value`

**Comment by prometheanfire** [comment]
I'm getting useless data for temperature (at least for temperature, probably more).  It seems like raw_value and value are reversed and min/max are not valid either.

I'm running version 7.0 of smartmontools.

Actual temp of the drive is 42°C
```
194 Temperature_Celsius     -O----   142   142   000    -    42 (Min/Max 21/52)
```

```
smartmon_temperature_celsius_raw_value{disk="/dev/sda",type="sat",smart_id="194"} 4.200000e+01
smartmon_temperature_celsius_threshold{disk="/dev/sda",type="sat",smart_id="194"} 0
smartmon_temperature_celsius_value{disk="/dev/sda",type="sat",smart_id="194"} 142
smartmon_temperature_celsius_worst{disk="/dev/sda",type="sat",smart_id="194"} 142
```

smart 7.1 shows the same
```
smartmon_temperature_celsius_raw_value{disk="/dev/sda",type="sat",smart_id="194"} 4.200000e+01
smartmon_temperature_celsius_threshold{disk="/dev/sda",type="sat",smart_id="194"} 0
smartmon_temperature_celsius_value{disk="/dev/sda",type="sat",smart_id="194"} 142
smartmon_temperature_celsius_worst{disk="/dev/sda",type="sat",smart_id="194"} 142
```

**Comment by candlerb** [comment]
raw_value of 42 or 43 (degrees celsius) looks fine to me.

Smartmon "cooked" or "normalized" [attributes](https://en.wikipedia.org/wiki/S.M.A.R.T.#ATA_S.M.A.R.T._attributes) are pretty useless in general.  They are supposed to be scaled to the range 1 to 253 of "worst" to "best".  Generally this is [undocumented](https://www.smartmontools.org/wiki/AttributesSeagate) and often makes no sense, e.g. what's a bad or good value of "power on hours"?

When you say "min/max are not valid either": they are simply not returned in the prometheus metrics.  The "worst" value is what the drive reports as the worst cooked value seen.

It might be possible to parse and return the raw min/max values as shown by smartctl, but that would be a separate feature request.  (I don't think I've ever seen it, but I am running smartmontools 6.5 or earlier)

**Comment by lheckemann** [comment]
I opened PR #75 which fixes the multi-disk issue; I think with that all the points raised here should be addressed?
