### ISSUE TITLE
Add nolog to storcli.py text collector

### ISSUE THREAD

**Issue by SckyzO** [prometheus-community/node-exporter-textfile-collector-scripts#82]
Hello team.
Thank you for your work. 

Just a little request. 
When I use storcli.py, it generate a .log
This log file is still quite "big" (250Kb for each request).
Would it be possible to add this option directly in the script?

Regards,

**Comment by dswarbrick** [comment]
Sounds reasonable to me. Do you want to submit a pull request?

**Comment by SckyzO** [comment]
I can :)
