### ISSUE TITLE
apt.sh include kept-back packages

### ISSUE THREAD

**Issue by alitoufighi** [prometheus-community/node-exporter-textfile-collector-scripts#90]
Hi. My use-case for this script was to check if we have updates for our mongodb server machines. However, to reduce the risk of accidentally running `apt upgrade` and upgrading the mongodb binaries, we have kept them back. These are the exact packages I wanted their results in my metrics, but because of them not being upgraded by `apt upgrade`, they are not shown in the captured result by this script.
I tried adding `--with-new-pkgs` to the executed `apt --just-print upgrade` command, but it complains:
```
E: Command line option --with-new-pkgs is not understood in combination with the other options
```
Is there any solution to what I want here?

**Comment by dswarbrick** [comment]
How about adding the `--ignore-hold` option?

**Comment by alitoufighi** [comment]
This is indeed the solution I was looking for. Isn't it better to include this option in the command we execute to gather the package updates?

**Comment by kyrofa** [comment]
Given issues like #85 I think we should consider moving away from the CLI entirely.

**Comment by kyrofa** [comment]
Alright check out #99. I even added a `apt_upgrades_held` metric for you.
