### ISSUE TITLE
smartmon.py increases IO time

### ISSUE THREAD

**Issue by Redsandro** [prometheus-community/node-exporter-textfile-collector-scripts#93]
Smartmon.py seems to add to the overall IO time measurements. It can't be the script executing, right? So perhaps it is the `smartctl` call itself. 

https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/414fb44693444cb96a55c7152cdd84d531888e1f/smartmon.py#L125-L127

I've tried this out on an idle machine. The red line is where I added this collector:

![image](https://user-images.githubusercontent.com/1702193/113138582-43de8080-9226-11eb-9ab0-ae18d8c48d55.png)

```
sum by (instance) (irate(node_disk_io_time_seconds_total[5m]))
```

How come smartctl adds disk IO?

**Comment by dswarbrick** [comment]
SMART commands are ATA commands just like any other read / write ATA commands. Different devices / vendors have better / worse SMART implementations in their firmware.

And yes, I've also seen SMART commands caused small but measurable latency in the past. Judging by your graph, it is incurring about a 0.005 ms (5 µs) latency. Does 5µs have a big impact on you, considering most disk IO requests will be in the order of a few milliseconds?

**Comment by Redsandro** [comment]
Nah, I guess it doesn't have a realistic impact. I was just puzzled because I misunderstood the way SMART commands are communicated. I thought they were values sitting in a chip that could be read without an IO impact. I will close this issue.
